package com.demo.urlshortener.controller;

import com.demo.urlshortener.dto.ShortenRequest;
import com.demo.urlshortener.dto.ShortenResponse;
import com.demo.urlshortener.service.UrlService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * REST controller exposing the two core URL-shortener endpoints.
 *
 * <p>All business logic is delegated to {@link UrlService}. This controller is
 * intentionally thin: it handles HTTP concerns only (status codes, headers,
 * request/response mapping).
 *
 * <p>Error responses for known failure cases are produced by
 * {@link com.demo.urlshortener.exception.GlobalExceptionHandler}.
 */
@RestController
@RequiredArgsConstructor
public class UrlController {

    private final UrlService urlService;

    /**
     * Creates a new short URL mapping.
     *
     * <p>Accepts an optional {@code alias} field in the request body. When absent,
     * a short code is auto-generated by Base62-encoding the new record's database ID.
     * When present, the alias is used verbatim after a uniqueness check.
     *
     * @param request validated request body containing the original URL, optional alias,
     *                and optional expiration timestamp
     * @return {@code 201 Created} with a {@link ShortenResponse} body containing the
     *         generated short URL, short code, original URL, and timestamps
     * @throws com.demo.urlshortener.exception.AliasAlreadyExistsException if the
     *         requested alias is already registered (results in {@code 409 Conflict})
     */
    @PostMapping("/shorten")
    public ResponseEntity<ShortenResponse> shorten(@Valid @RequestBody ShortenRequest request) {
        ShortenResponse response = urlService.shorten(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Resolves a short code and redirects the client to the original URL.
     *
     * <p>Returns a {@code 302 Found} response with a {@code Location} header pointing
     * to the destination URL. Expired or unknown short codes return {@code 404 Not Found}.
     *
     * @param shortCode the short code path segment (e.g., {@code abc123} from
     *                  {@code http://localhost:8080/abc123})
     * @return {@code 302 Found} with the {@code Location} header set to the original URL
     * @throws com.demo.urlshortener.exception.UrlNotFoundException if the short code
     *         does not exist or its URL has expired (results in {@code 404 Not Found})
     */
    @GetMapping("/{shortCode}")
    public ResponseEntity<Void> redirect(@PathVariable String shortCode) {
        String originalUrl = urlService.resolve(shortCode);
        return ResponseEntity.status(HttpStatus.FOUND)
                .header(HttpHeaders.LOCATION, originalUrl)
                .build();
    }
}
